# Generated by Django 3.2.5 on 2023-10-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finecontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleApplication_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120, null=True)),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finecontrol.method_db')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZeroPosition_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_x', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('zero_y', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sample_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zero_properties', to='sampleapp.sampleapplication_db')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PressureSettings_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nozzlediameter', models.CharField(default='0.08', max_length=120)),
                ('rinsingPeriod', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('sample_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pressure_settings', to='sampleapp.sampleapplication_db')),
            ],
        ),
        migrations.CreateModel(
            name='PlateProperties_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_x', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('size_y', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('offset_left', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('offset_right', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('offset_top', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('offset_bottom', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sample_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_properties', to='sampleapp.sampleapplication_db')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovementSettings_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_speed', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('delta_x', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('delta_y', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sample_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_settings', to='sampleapp.sampleapplication_db')),
            ],
        ),
        migrations.CreateModel(
            name='BandSettings_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_property', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('value', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('gap', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('waitTime', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sample_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_settings', to='sampleapp.sampleapplication_db')),
            ],
        ),
        migrations.CreateModel(
            name='BandsComponents_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('product_name', models.CharField(blank=True, max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('type', models.CharField(blank=True, max_length=120, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('viscosity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sample_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_components', to='sampleapp.sampleapplication_db')),
            ],
        ),
    ]
