# Generated by Django 3.2.5 on 2023-12-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandscomponents_db',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bandscomponents_db',
            name='region',
        ),
        migrations.RemoveField(
            model_name='bandscomponents_db',
            name='year',
        ),
    ]
