# Generated by Django 3.2.5 on 2023-10-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyringeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_type', models.CharField(choices=[('3', '2 ml'), ('6', '5 ml'), ('12', '10 ml')], default=('3', '2 ml'), max_length=255, null=True)),
                ('length_type', models.CharField(choices=[('40', '40 mm'), ('49', '49 mm'), ('60', '60 mm')], default=('40', '40 mm'), max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZeroPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_x', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('zero_y', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyringeLoad_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Method_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120, null=True)),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GcodeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('gcode', models.FileField(null=True, upload_to='')),
                ('gcode_url', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningProcess_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_frequency', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('stop_frequency', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('steps', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('times', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirSensor_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
