# Generated by Django 3.2.5 on 2024-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syringeconfiguration',
            name='length_type',
            field=models.CharField(choices=[('40', '40 mm'), ('50', '50 mm'), ('60', '60 mm')], default=('40', '40 mm'), max_length=255, null=True),
        ),
    ]
