# Generated by Django 3.2.5 on 2024-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plateproperties_db',
            name='size_x',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='plateproperties_db',
            name='size_y',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='pressuresettings_dev_db',
            name='motor_speed',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pressuresettings_dev_db',
            name='pressure',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='pressuresettings_dev_db',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
